# Generated by Django 5.2.10 on 2026-02-02 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("annonces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ads",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vendeur",
            ),
        ),
        migrations.AddField(
            model_name="adcontact",
            name="ad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="annonces.ad",
                verbose_name="Annonce",
            ),
        ),
        migrations.AddField(
            model_name="adcontact",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_contacts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Expéditeur",
            ),
        ),
        migrations.AddField(
            model_name="adimage",
            name="ad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="annonces.ad",
                verbose_name="Annonce",
            ),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                fields=["status", "is_active"], name="annonces_ad_status_46f64e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                fields=["category"], name="annonces_ad_categor_318d18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                fields=["region", "department"], name="annonces_ad_region_a19cd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                fields=["-created_at"], name="annonces_ad_created_c9b30f_idx"
            ),
        ),
    ]
